get http://localhost:2107/api/tipoCampeon

###

get http://localhost:2107/api/tipoCampeon/638bfbe3761d1364402ec57c

###

post http://localhost:2107/api/tipoCampeon
Content-Type: application/json

 {
    "tipoTipoCampeon": "Sanador"
 }
###

put http://localhost:2107/api/tipoCampeon/63894f525a773b9805cfa941
Content-Type: application/json

 {
    "tipoTipoCampeon": "Tirador"
 }


###

delete http://localhost:2107/api/tipoCampeon/63894f525a773b9805cfa941
