get http://localhost:2107/api/tipoCampeon

###

get http://localhost:2107/api/tipoCampeon/638d739b2930c476fc9acd16

###

post http://localhost:2107/api/tipoCampeon
Content-Type: application/json

 {
    "tipoTipoCampeon": "Asesino"
 }
###

put http://localhost:2107/api/tipoCampeon/638d739b2930c476fc9acd16
Content-Type: application/json

 {
    "tipoTipoCampeon": "Tirador"
 }


###

delete http://localhost:2107/api/tipoCampeon/638d739b2930c476fc9acd16
