get http://localhost:2107/api/linea

###

get http://localhost:2107/api/linea/638d0ed53adcd209162e3897
###

post http://localhost:2107/api/linea
Content-Type: application/json

 {
  "tipoLinea":"Top",
  "descripcion":"En esta linea se juganar luchadores y tanques"
 }
###

put http://localhost:2107/api/linea/638d0ed53adcd209162e3897
Content-Type: application/json

 {
  "tipoLinea":"Midlane"
 }


###

delete http://localhost:2107/api/linea/638d0ed53adcd209162e3897
