get http://localhost:2107/api/linea

###

get http://localhost:2107/api/linea/637d8167af5369293411a51e

###

post http://localhost:2107/api/linea
Content-Type: application/json

 {
  "tipoLinea":"Midlane",
  "descripcion":"En esta linea jugaran los tiradores campeones de rango"
 }
###

put http://localhost:2107/api/linea/637d814eaf5369293411a51c
Content-Type: application/json

 {
  "tipoLinea":"Midlane"
 }


###

delete http://localhost:2107/api/linea/637d8167af5369293411a51e
