get http://localhost:2107/api/personaje

###

get http://localhost:2107/api/personaje/638d73df2930c476fc9acd1c
###

post http://localhost:2107/api/personaje/638d739b2930c476fc9acd16/638d0ed53adcd209162e3897
Content-Type: application/json

 {
  "nombre":"Talon"

 }
###

put http://localhost:2107/api/personaje/638b8163b35ba8e36fb66750
Content-Type: application/json

 {
  "nombre":"Midlane"
 }


###

delete http://localhost:2107/api/personaje/638b8929bd590d046b1562bd
