get http://localhost:2107/api/linea

###

post http://localhost:2107/api/linea
Content-Type: application/json

 {
   "tipoLinea":"Suport",
  "descripcion":"El soporte es el que cuida al adc"
 }

###

put http://localhost:2107/api/linea/456

###

delete http://localhost:2107/api/linea/637d7564bf61e0239c04b676
