get http://localhost:3000/linea

###

post http://localhost:3000/linea
Content-Type: application/json

 {
  "tipoLinea": "Mid",
  "descripcion":"En esta linea se jugaran magos y asesinos"
 }

###

put http://localhost:3000/linea/456

###

delete http://localhost:3000/linea/5
